package:
  name: foxpost
  version: 1.3.0
  description: Luna's blog
  copyright:
    - license: GPL-2.0-only
      paths:
        - "*"
  dependencies:
    runtime:
      - libpq-15
      - ca-certificates-bundle
      - wolfi-baselayout

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - clang-15
      - llvm15-dev
      - libLLVM-15
      - mold
      - build-base
      - wolfi-baselayout
      - ca-certificates-bundle
      - pkgconf
      - libpq-15
      - postgresql-15-dev
      - busybox
      - nodejs-20
      - yarn
      - rust
pipeline:
  - name: Build Luna's blog
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      BLOG_HOME="${{targets.destdir}}/"
      TARGETDIR="/var/cache/melange/blog"
      mkdir -p "${BLOG_HOME}/media" "${EXEC_DIR}"
      cargo build --release --target-dir "${TARGETDIR}"
      cd static_src
      yarn && yarn compile:prod
      cd ..
      cp "${TARGETDIR}/release/foxpost" "${EXEC_DIR}"
      cp -rv static    "${{targets.destdir}}/static"
      cp -rv templates "${{targets.destdir}}/templates"
      mkdir "${{targets.destdir}}/assets"
      chmod -R +r "${{targets.destdir}}/assets"
