package:
  name: Lunas-blog
  version: 0.1.3
  description: Luna's blog
  target-architecture:
    - amd64
    - aarch64
  copyright:
    - license: GPL-2.0-only
      paths:
        - "*"
  dependencies:
    runtime:
      - libpq-15
      - ca-certificates-bundle

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - clang-15
      - gcc
      - mold
      - glibc-dev
      - wolfi-baselayout
      - ca-certificates-bundle
      - pkgconf
      - libpq-15
      - postgresql-15-dev
      - busybox
      - rust
pipeline:
  - name: Build Luna's blog
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      BLOG_HOME="${{targets.destdir}}/"      
      TARGETDIR="$(mktemp -d)"
      mkdir -p "${BLOG_HOME}/media" "${EXEC_DIR}"
      cargo build --release --target-dir "${TARGETDIR}"
      cp "${TARGETDIR}/release/blog" "${EXEC_DIR}"
      cp -rv static    "${{targets.destdir}}/static"
      cp -rv templates "${{targets.destdir}}/templates"
      mkdir "${{targets.destdir}}/assets"