package:
  name: Lunas-blog
  version: 1.0.2
  description: Luna's blog
  target-architecture:
    - amd64
    - aarch64
  copyright:
    - license: GPL-2.0-only
      paths:
        - "*"
  dependencies:
    runtime:
      - libpq-15
      - ca-certificates-bundle

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    packages:
      - gcc
      - glibc-dev
      - wolfi-baselayout
      - ca-certificates-bundle
      - pkgconf
      - libpq-15
      - postgresql-15-dev
      - busybox
      - nodejs-19
      - rust
pipeline:
  - name: Build Luna's blog
    runs: |
      EXEC_DIR="${{targets.destdir}}/usr/bin"
      BLOG_HOME="${{targets.destdir}}/"
      TARGETDIR="/var/cache/melange/blog"
      mkdir -p "${BLOG_HOME}/media" "${EXEC_DIR}"
      npm install --global yarn
      rm -rf .cargo
      cargo build --release --target-dir "${TARGETDIR}"
      cd tailwind
      yarn && yarn compile --minify
      cd ..
      cp "${TARGETDIR}/release/blog" "${EXEC_DIR}"
      cp -rv static    "${{targets.destdir}}/static"
      cp -rv templates "${{targets.destdir}}/templates"
      mkdir "${{targets.destdir}}/assets"
      chmod -R +r "${{targets.destdir}}/assets"
