-- Your SQL goes here
CREATE TABLE tags (
    tag VARCHAR(20) NOT NULL PRIMARY KEY
);

CREATE TABLE tagposts (
    tag VARCHAR(20) NOT NULL PRIMARY KEY,
    post TEXT [] NOT NULL
);

ALTER TABLE Posts
ADD tags TEXT [] NOT NULL;