

on:
  push:
    branches:
      - mistress

name: Release Packaging

jobs:
  release:
    name: Release Packaging
    env:
      PROJECT_NAME: blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: sudo apt install -y mold clang
      - name: Release Build
        run: cargo build --release --target x86_64-unknown-linux-gnu
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PROJECT_NAME }}
          path: target/release/${{ env.PROJECT_NAME }}
